/**
*Author:        author
*Company:       company
*Description:   State class corresponding to the Object__c Custom Object. Methods from the Helper class to be added only if relevant to trigger state defined.
*History
*<Date>        <Authors Name>     <Brief Description of Change>
*2/14/2020      author             Initial version created.    
**/
public class ObjectStateTemplate extends TriggerHandlerBase {

    public override void mainEntry(TriggerParameters tp) {
        //ObjectHelperTemplate.methodName((List<sObject>)tp.newList);
    }
}